AllCops:
  Include:
    - config.ru
  Exclude:
    - spec/*
    - activerecord_routes.gemspec
    - bin/*
    - config.ru

Style/DotPosition:
  EnforcedStyle: trailing
  Enabled: true

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/MultilineOperationIndentation:
  EnforcedStyle: indented
